# Import imp library

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn import tree

In [27]:
df = pd.read_csv(r"C:\Users\deves\Documents\GitHub\Free_Datasets\Data Sets\titanic.csv")
df = df.rename(columns={i:i.lower() for i in df.columns})
df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerid  891 non-null    int64
 1   survived     891 non-null    int64
 2   pclass       891 non-null    int64
 3   name         891 non-null    object
 4   sex          891 non-null    object
 5   age          714 non-null    float64
 6   sibsp        891 non-null    int64
 7   parch        891 non-null    int64
 8   ticket       891 non-null    object
 9   fare         891 non-null    float64
 10  cabin        204 non-null    object
 11  embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
df.describe().round(2)

       passengerid  survived  pclass     age   sibsp   parch    fare
count       891.00    891.00  891.00  714.00  891.00  891.00  891.00
mean        446.00      0.38    2.31   29.70    0.52    0.38   32.20
std         257.35      0.49    0.84   14.53    1.10    0.81   49.69
min           1.00      0.00    1.00    0.42    0.00    0.00    0.00
25%         223.50      0.00    2.00   20.12    0.00    0.00    7.91
50%         446.00      0.00    3.00   28.00    0.00    0.00   14.45
75%         668.50      1.00    3.00   38.00    1.00    0.00   31.00
max         891.00      1.00    3.00   80.00    8.00    6.00  512.33

In [7]:
df.isnull().sum()

passengerid      0
survived         0
pclass           0
name             0
sex              0
age            177
sibsp            0
parch            0
ticket           0
fare             0
cabin          687
embarked         2
dtype: int64

In [8]:
# keep usefull columns
print(df.columns)

Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='object')

In [9]:
df = df.drop(columns=['passengerid','name','ticket'])

In [10]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare cabin embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [11]:
# clean age columns
df['age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: age, dtype: float64

In [12]:
df['age'] = df['age'].fillna(df['age'].median())

In [13]:
# clean cabin
df.cabin

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: cabin, Length: 891, dtype: object

In [14]:
df['cabin'] = df.cabin.notnull()

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   cabin     891 non-null    bool
 8   embarked  889 non-null    object
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [16]:
df.isnull().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
cabin       0
embarked    2
dtype: int64

In [17]:
# clean embarked
df.embarked.value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [18]:
df.embarked.fillna("S",inplace=True)

/tmp/ipykernel_601/979550661.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.embarked.fillna("S",inplace=True)

In [19]:
# rename columns in all lower

x = df.drop(columns="survived")
y = df['survived']

In [20]:
x

     pclass     sex   age  sibsp  parch     fare  cabin embarked
0         3    male  22.0      1      0   7.2500  False        S
1         1  female  38.0      1      0  71.2833   True        C
2         3  female  26.0      0      0   7.9250  False        S
3         1  female  35.0      1      0  53.1000   True        S
4         3    male  35.0      0      0   8.0500  False        S
..      ...     ...   ...    ...    ...      ...    ...      ...
886       2    male  27.0      0      0  13.0000  False        S
887       1  female  19.0      0      0  30.0000   True        S
888       3  female  28.0      1      2  23.4500  False        S
889       1    male  26.0      0      0  30.0000   True        C
890       3    male  32.0      0      0   7.7500  False        Q

[891 rows x 8 columns]

In [21]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [22]:
# Decision Trees do not require feature scaling.
# Decision Trees do need encoding if your dataset contains categorical (text) features.
# you need to remove null values only

In [23]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    891 non-null    int64
 1   sex       891 non-null    object
 2   age       891 non-null    float64
 3   sibsp     891 non-null    int64
 4   parch     891 non-null    int64
 5   fare      891 non-null    float64
 6   cabin     891 non-null    bool
 7   embarked  891 non-null    object
dtypes: bool(1), float64(2), int64(3), object(2)
memory usage: 49.7+ KB

In [28]:
encoder = OneHotEncoder()
encoded_x = encoder.fit_transform(x[df.select_dtypes("object").columns ])

In [24]:
model = DecisionTreeClassifier()

In [29]:
model.fit(encoded_x,y)

DecisionTreeClassifier()

In [31]:
prediction = model.predict(encoded_x)

In [32]:
accuracy_score(y,prediction)

0.7867564534231201