# Pandas Library

In [1]:
import pandas as pd
import numpy as np

# Series

In [ ]:
s = pd.Series([230,450,980,500,1200])
print(s)

In [ ]:
# Try  +   -    *    /  //   **  %

s * 2

# Indexing and slicing

In [ ]:
print(s)

In [ ]:
s[2] = 552

In [ ]:
# Negative indexing does not work in the series 
s[-1]

In [ ]:
print(s)

In [ ]:
s[1:4]

# Name index

In [ ]:
age = pd.Series({"rohan":34,"kunal":78,"kartik":23,"mohit":12,"naman":46})
print(age)

In [ ]:
age['kunal']

In [ ]:
age['kunal'] = 44
print(age)

In [ ]:
age['kunal':'mohit']

# Attributes in Pandas series

In [ ]:
age

In [ ]:
age.index

In [ ]:
age.values

In [ ]:
age.dtype

In [ ]:
age.shape

In [ ]:
age.size

In [ ]:
age.ndim

In [ ]:
age.name

# Aggregate functions in series

In [ ]:
sales = pd.Series([560,340,210,980,564,340,340])
sales

In [ ]:
sales.sum()

In [ ]:
sales.min()

In [ ]:
sales.max()

In [ ]:
sales.mean()    # average

In [ ]:
sales.median()

In [ ]:
sales.mode()

In [ ]:
sales.std()

In [ ]:
sales.var()

In [ ]:
sales.count()

# np.where

In [ ]:
import numpy as np

print(sales)

np.where(sales>=500 , "good", "bad")

# apply method

In [ ]:
print(sales)

def find_category(amount):
    if amount<400:
        return "Low"
    elif amount < 700:
        return "Mid"
    else:
        return "High"

sales.apply(find_category)

In [ ]:
sales.apply(lambda amount : amount*0.05 if amount<=500 else amount*0.10)

# Data Frame

In [ ]:
import os

os.listdir()

In [ ]:
os.getcwd()

In [3]:
# if the file is in same folder 
df = pd.read_csv("store.csv")

In [ ]:
# if file is not in the same folder 
df = pd.read_csv(r"C:\Users\deves\Documents\GitHub\Free_Datasets\Data Sets\store.csv")

In [ ]:
df

# Know about your data

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.describe().round(2)

In [ ]:
df.head(2)

In [ ]:
df.tail(2)

In [ ]:
df.sample(5)

In [ ]:
# check null values
df.isnull().sum()

In [ ]:
# getting a list of all columns
df.columns

# selecting single columns

In [ ]:
# single column
df['name']

In [ ]:
df['sales']

In [ ]:
# shortcut way to getting a column
df.sales

# Selecting multiple columns

In [ ]:
col = ['name','sales','profit']
df[col]

In [ ]:
df[['name','sales','profit']]

# Creating new columns

In [4]:
df.head(2)

,order_id,order_date,name,city,state,post_code,region,category,sub_category,sales,qty,profit
0,CA-2016-155488,2016-11-13 00:00:00,Frank Merwin,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
1,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18

In [ ]:
df['new'] = 100

In [ ]:
df['cost'] = df['sales'] - df['profit']

In [ ]:
df.head(2)

In [ ]:
# create a new column unit price (sales/qty)

In [ ]:
# creating new column sales category using np.where If the sales amount is above 1000 it is high else low?  

df['sales_category'] = np.where(df['sales']>=1000 ,"High","Low")
df.head()

In [8]:
# Create a new column for sales category low Medium and High?
def sales_cat(amount):
    if amount <= 100:
        return "Low"
    elif amount <= 1000:
        return "Mid"
    else:
        return "High"

df['sales_category'] = df['sales'].apply(sales_cat)

In [13]:
df.head()

,order_id,order_date,name,city,state,post_code,region,category,sub_category,sales,qty,profit,sales_category
0,CA-2016-155488,2016-11-13 00:00:00,Frank Merwin,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45,Low
1,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18,High
2,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Furniture,Tables,1090.78,7,-290.88,High
3,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Office Supplies,Paper,19.44,3,9.33,Low
4,CA-2015-126445,2015-08-27 00:00:00,Ryan Akin,Murrieta,California,NaN,West,Office Supplies,Storage,484.65,3,92.08,Mid

# delete columns and rows

In [16]:
df.drop(columns="city")   # temp
df = df.drop(columns="sales_category")   # permanent delete

In [17]:
df.head(2)

,order_id,order_date,name,city,state,post_code,region,category,sub_category,sales,qty,profit
0,CA-2016-155488,2016-11-13 00:00:00,Frank Merwin,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
1,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18

In [21]:
df.drop(index=2)

,order_id,order_date,name,city,state,post_code,region,category,sub_category,sales,qty,profit
0,CA-2016-155488,2016-11-13 00:00:00,Frank Merwin,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
1,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18
3,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Office Supplies,Paper,19.44,3,9.33
4,CA-2015-126445,2015-08-27 00:00:00,Ryan Akin,Murrieta,California,NaN,West,Office Supplies,Storage,484.65,3,92.08
5,CA-2015-111199,2015-11-13 00:00:00,Joe Kamberova,Jacksonville,North Carolina,NaN,South,Office Supplies,Paper,115.30,3,40.35
...,...,...,...,...,...,...,...,...,...,...,...,...
495,CA-2017-152485,2017-09-04 00:00:00,John Dryer,Coppell,Texas,75019.0,Central,Office Supplies,Art,10.19,7,3.19
496,CA-2017-152485,2017-09-04 00:00:00,John Dryer,Coppell,Texas,75019.0,Central,Office Supplies,Storage,16.78,1,-0.21
497,CA-2017-152485,2017-09-04 00:00:00,John Dryer,Coppell,Texas,75019.0,Central,Office Supplies,Art,13.12,5,3.77
498,CA-2016-141586,2016-10-17 00:00:00,Neil Knudson,San Francisco,California,94122.0,West,Office Supplies,Binders,18.16,5,6.58
499,CA-2017-130386,2017-11-12 00:00:00,Nathan Gelder,Austin,Texas,78745.0,Central,Office Supplies,Paper,16.06,3,5.82

In [22]:
df.drop(index=[0,2,3])

,order_id,order_date,name,city,state,post_code,region,category,sub_category,sales,qty,profit
1,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18
4,CA-2015-126445,2015-08-27 00:00:00,Ryan Akin,Murrieta,California,NaN,West,Office Supplies,Storage,484.65,3,92.08
5,CA-2015-111199,2015-11-13 00:00:00,Joe Kamberova,Jacksonville,North Carolina,NaN,South,Office Supplies,Paper,115.30,3,40.35
6,CA-2015-105312,2015-11-06 00:00:00,Meg Tillman,Scottsdale,Arizona,NaN,West,Office Supplies,Envelopes,7.08,3,2.48
7,CA-2015-105312,2015-11-06 00:00:00,Meg Tillman,Scottsdale,Arizona,NaN,West,Office Supplies,Binders,4.40,3,-3.52
...,...,...,...,...,...,...,...,...,...,...,...,...
495,CA-2017-152485,2017-09-04 00:00:00,John Dryer,Coppell,Texas,75019.0,Central,Office Supplies,Art,10.19,7,3.19
496,CA-2017-152485,2017-09-04 00:00:00,John Dryer,Coppell,Texas,75019.0,Central,Office Supplies,Storage,16.78,1,-0.21
497,CA-2017-152485,2017-09-04 00:00:00,John Dryer,Coppell,Texas,75019.0,Central,Office Supplies,Art,13.12,5,3.77
498,CA-2016-141586,2016-10-17 00:00:00,Neil Knudson,San Francisco,California,94122.0,West,Office Supplies,Binders,18.16,5,6.58
499,CA-2017-130386,2017-11-12 00:00:00,Nathan Gelder,Austin,Texas,78745.0,Central,Office Supplies,Paper,16.06,3,5.82

# Rename a column

In [23]:
df.head(2)

,order_id,order_date,name,city,state,post_code,region,category,sub_category,sales,qty,profit
0,CA-2016-155488,2016-11-13 00:00:00,Frank Merwin,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
1,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18

In [24]:
df.rename(columns={"city":"location"})

,order_id,order_date,name,location,state,post_code,region,category,sub_category,sales,qty,profit
0,CA-2016-155488,2016-11-13 00:00:00,Frank Merwin,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
1,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18
2,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Furniture,Tables,1090.78,7,-290.88
3,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Office Supplies,Paper,19.44,3,9.33
4,CA-2015-126445,2015-08-27 00:00:00,Ryan Akin,Murrieta,California,NaN,West,Office Supplies,Storage,484.65,3,92.08
...,...,...,...,...,...,...,...,...,...,...,...,...
495,CA-2017-152485,2017-09-04 00:00:00,John Dryer,Coppell,Texas,75019.0,Central,Office Supplies,Art,10.19,7,3.19
496,CA-2017-152485,2017-09-04 00:00:00,John Dryer,Coppell,Texas,75019.0,Central,Office Supplies,Storage,16.78,1,-0.21
497,CA-2017-152485,2017-09-04 00:00:00,John Dryer,Coppell,Texas,75019.0,Central,Office Supplies,Art,13.12,5,3.77
498,CA-2016-141586,2016-10-17 00:00:00,Neil Knudson,San Francisco,California,94122.0,West,Office Supplies,Binders,18.16,5,6.58
499,CA-2017-130386,2017-11-12 00:00:00,Nathan Gelder,Austin,Texas,78745.0,Central,Office Supplies,Paper,16.06,3,5.82

In [30]:
# df.columns

In [31]:
# for i in df.columns:
#     print(i,i.upper())

In [32]:
# df.rename(columns={ i : i.upper() for i in df.columns})