In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("store.csv")

In [2]:
s = pd.Series([230,450,980,500,1200])

In [3]:
s * 2

0     460
1     900
2    1960
3    1000
4    2400
dtype: int64

In [4]:
s[2] = 885

In [5]:
s

0     230
1     450
2     885
3     500
4    1200
dtype: int64

In [6]:
s[s >= 500]

2     885
3     500
4    1200
dtype: int64

In [7]:
s

0     230
1     450
2     885
3     500
4    1200
dtype: int64

In [8]:
country = pd.Series({"india":8900,"china":3490,"russia":1200,"america":3892})

In [9]:
country

india      8900
china      3490
russia     1200
america    3892
dtype: int64

In [10]:
country["russia"]

np.int64(1200)

In [11]:
s

0     230
1     450
2     885
3     500
4    1200
dtype: int64

In [12]:
s[1:4]

1    450
2    885
3    500
dtype: int64

In [13]:
country['india':'russia']

india     8900
china     3490
russia    1200
dtype: int64

In [14]:
country.index

Index(['india', 'china', 'russia', 'america'], dtype='object')

In [15]:
country.values

array([8900, 3490, 1200, 3892])

In [16]:
country.dtype

dtype('int64')

In [18]:
country.shape

(4,)

In [19]:
country.size

4

In [20]:
country.ndim

1

In [21]:
country.mean()

np.float64(4370.5)

In [22]:
country.median()

np.float64(3691.0)

In [23]:
country.mode()

0    1200
1    3490
2    3892
3    8900
dtype: int64

In [24]:
sum(country)

17482

In [3]:
df = pd.read_csv("store.csv")

In [6]:
df

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
0,1001,CA-2016-155488,2016-11-13 00:00:00,Standard Class,FM-14290,Frank Merwin,Home Office,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
1,1002,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18
2,1003,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Furniture,Tables,1090.78,7,-290.88
3,1004,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Office Supplies,Paper,19.44,3,9.33
4,1005,CA-2015-126445,2015-08-27 00:00:00,Standard Class,RA-19945,Ryan Akin,Consumer,Murrieta,California,NaN,West,Office Supplies,Storage,484.65,3,92.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1496,CA-2017-152485,2017-09-04 00:00:00,Standard Class,JD-15790,John Dryer,Consumer,Coppell,Texas,75019.0,Central,Office Supplies,Art,10.19,7,3.19
496,1497,CA-2017-152485,2017-09-04 00:00:00,Standard Class,JD-15790,John Dryer,Consumer,Coppell,Texas,75019.0,Central,Office Supplies,Storage,16.78,1,-0.21
497,1498,CA-2017-152485,2017-09-04 00:00:00,Standard Class,JD-15790,John Dryer,Consumer,Coppell,Texas,75019.0,Central,Office Supplies,Art,13.12,5,3.77
498,1499,CA-2016-141586,2016-10-17 00:00:00,First Class,NK-18490,Neil Knudson,Home Office,San Francisco,California,94122.0,West,Office Supplies,Binders,18.16,5,6.58
499,1500,CA-2017-130386,2017-11-12 00:00:00,Standard Class,NG-18430,Nathan Gelder,Consumer,Austin,Texas,78745.0,Central,Office Supplies,Paper,16.06,3,5.82

In [11]:
df['sales'].median()

np.float64(47.965)

In [13]:
df.sales.mean()

np.float64(215.92765999999997)

In [14]:
df.profit.max()

np.float64(2400.97)

In [16]:
import numpy as np

In [17]:
np.where(df.sales > 500 ,"Big","Small")

array(['Small', 'Big', 'Big', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Big', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Big', 'Small', 'Big', 'Big',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Big', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Big', 'Small', 'Big', 'Small', 'Small',
       'Small', 'Big', 'Small', 'Big', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Big', 'Big', 'Small', 'Small', 'Big', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Big', 'Small', 'Small', 'Big', 'Small', 'Small', 'Small',
       'Small', 'Big', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Big', 'Small', 'Big',
       'Small', 'Small', 'Small', 'Big', 'Small', 'Small', 'Small',
       'Small', 'Big', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Big', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Big', 'Big', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Big', 'Big', 'Small', 'Big', 'Big', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Big',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Big', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Big', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Big', 'Big', 'Small',
       'Small', 'Big', 'Big', 'Small', 'Big', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Big', 'Small', 'Big', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Big', 'Small', 'Small', 'Small',
       'Small', 'Big', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Big', 'Small', 'Big', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Big', 'Small', 'Small', 'Big', 'Small', 'Big', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Big', 'Small', 'Big', 'Small', 'Small',
       'Small', 'Small', 'Big', 'Big', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Big', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Big', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Big', 'Small', 'Small',
       'Small', 'Small', 'Big', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Big', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Big', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Big',
       'Small', 'Small', 'Small', 'Small', 'Big', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small',
       'Small', 'Big', 'Small', 'Small', 'Small', 'Small', 'Small', 'Big',
       'Small', 'Small', 'Small', 'Small', 'Small', 'Small', 'Small'],
      dtype='<U5')

In [23]:
np.where((df.sales > 1000) & (df.category == "Furniture"), "Yes","No")

array(['No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No'], dtype='<U3')

In [24]:
df.sales

0        44.02
1      2309.65
2      1090.78
3        19.44
4       484.65
        ...
495      10.19
496      16.78
497      13.12
498      18.16
499      16.06
Name: sales, Length: 500, dtype: float64

In [25]:
def discount(amount):
    if amount>1000:
        return amount*12/100
    else:
        return 0

In [26]:
df.sales.apply(discount)

0        0.0000
1      277.1580
2      130.8936
3        0.0000
4        0.0000
         ...
495      0.0000
496      0.0000
497      0.0000
498      0.0000
499      0.0000
Name: sales, Length: 500, dtype: float64

In [29]:
df.profit.apply(lambda x : "Profit" if x>0 else "Loss")

0      Profit
1      Profit
2        Loss
3      Profit
4      Profit
        ...
495    Profit
496      Loss
497    Profit
498    Profit
499    Profit
Name: profit, Length: 500, dtype: object

In [7]:
df.sample(5)

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
68,1069,US-2017-139955,2017-09-28 00:00:00,Second Class,CM-12160,Charles McCrossin,Consumer,Brownsville,Texas,78521.0,Central,Office Supplies,Supplies,1.74,1,-0.35
278,1279,CA-2014-163293,2014-09-08 00:00:00,First Class,KC-16255,Karen Carlisle,Corporate,Macon,Georgia,31204.0,South,Technology,Accessories,32.97,3,12.86
58,1059,CA-2017-167150,2017-12-10 00:00:00,Standard Class,BP-11185,Ben Peterman,Corporate,San Diego,California,92037.0,West,Office Supplies,Binders,65.57,2,22.95
0,1001,CA-2016-155488,2016-11-13 00:00:00,Standard Class,FM-14290,Frank Merwin,Home Office,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
27,1028,CA-2016-126529,2016-01-11 00:00:00,Second Class,DE-13255,Deanra Eno,Home Office,Springfield,Ohio,NaN,East,Technology,Phones,15.59,2,-9.87

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            500 non-null    int64
 1   order_id      500 non-null    object
 2   order_date    500 non-null    object
 3   shipment      500 non-null    object
 4   customer_id   500 non-null    object
 5   name          500 non-null    object
 6   segment       500 non-null    object
 7   city          500 non-null    object
 8   state         500 non-null    object
 9   post_code     484 non-null    float64
 10  region        500 non-null    object
 11  category      500 non-null    object
 12  sub_category  500 non-null    object
 13  sales         500 non-null    float64
 14  qty           500 non-null    int64
 15  profit        500 non-null    float64
dtypes: float64(3), int64(2), object(11)
memory usage: 62.6+ KB

In [9]:
df.isnull().sum()

id               0
order_id         0
order_date       0
shipment         0
customer_id      0
name             0
segment          0
city             0
state            0
post_code       16
region           0
category         0
sub_category     0
sales            0
qty              0
profit           0
dtype: int64

In [10]:
df.shape

(500, 16)

In [13]:
df.describe()

                id     post_code        sales         qty       profit
count   500.000000    484.000000   500.000000  500.000000   500.000000
mean   1250.500000  51985.826446   215.927660    3.838000    26.771860
std     144.481833  32293.018231   453.710127    2.440424   176.891974
min    1001.000000   1841.000000     1.080000    1.000000 -1850.950000
25%    1125.750000  20016.000000    15.642500    2.000000     1.635000
50%    1250.500000  46350.000000    47.965000    3.000000     7.900000
75%    1375.250000  85204.000000   197.677500    5.000000    29.050000
max    1500.000000  98661.000000  4899.930000   14.000000  2400.970000

In [16]:
df.dtypes

id                int64
order_id         object
order_date       object
shipment         object
customer_id      object
name             object
segment          object
city             object
state            object
post_code       float64
region           object
category         object
sub_category     object
sales           float64
qty               int64
profit          float64
dtype: object

In [18]:
df['cost'] =  df.sales - df.profit

C:\Users\deves\AppData\Local\Temp\ipykernel_8292\544890946.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.cost =  df.sales - df.profit

In [2]:
df['hello'] = 100

In [6]:
df.head(2)

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
0,1001,CA-2016-155488,2016-11-13 00:00:00,Standard Class,FM-14290,Frank Merwin,Home Office,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
1,1002,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18

In [5]:
del df['hello']

In [8]:
df.drop(columns='city')

,id,order_id,order_date,shipment,customer_id,name,segment,state,post_code,region,category,sub_category,sales,qty,profit
0,1001,CA-2016-155488,2016-11-13 00:00:00,Standard Class,FM-14290,Frank Merwin,Home Office,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
1,1002,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York,NaN,East,Technology,Accessories,2309.65,7,762.18
2,1003,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York,NaN,East,Furniture,Tables,1090.78,7,-290.88
3,1004,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York,NaN,East,Office Supplies,Paper,19.44,3,9.33
4,1005,CA-2015-126445,2015-08-27 00:00:00,Standard Class,RA-19945,Ryan Akin,Consumer,California,NaN,West,Office Supplies,Storage,484.65,3,92.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1496,CA-2017-152485,2017-09-04 00:00:00,Standard Class,JD-15790,John Dryer,Consumer,Texas,75019.0,Central,Office Supplies,Art,10.19,7,3.19
496,1497,CA-2017-152485,2017-09-04 00:00:00,Standard Class,JD-15790,John Dryer,Consumer,Texas,75019.0,Central,Office Supplies,Storage,16.78,1,-0.21
497,1498,CA-2017-152485,2017-09-04 00:00:00,Standard Class,JD-15790,John Dryer,Consumer,Texas,75019.0,Central,Office Supplies,Art,13.12,5,3.77
498,1499,CA-2016-141586,2016-10-17 00:00:00,First Class,NK-18490,Neil Knudson,Home Office,California,94122.0,West,Office Supplies,Binders,18.16,5,6.58
499,1500,CA-2017-130386,2017-11-12 00:00:00,Standard Class,NG-18430,Nathan Gelder,Consumer,Texas,78745.0,Central,Office Supplies,Paper,16.06,3,5.82

In [10]:
df[['sales',"profit"]]

       sales  profit
0      44.02   11.45
1    2309.65  762.18
2    1090.78 -290.88
3      19.44    9.33
4     484.65   92.08
..       ...     ...
495    10.19    3.19
496    16.78   -0.21
497    13.12    3.77
498    18.16    6.58
499    16.06    5.82

[500 rows x 2 columns]

In [13]:
df[df.sales > 2000]

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
1,1002,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18
85,1086,US-2016-143819,2016-03-01 00:00:00,Standard Class,KD-16270,Karen Daniels,Consumer,Yonkers,New York,10701.0,East,Technology,Machines,4899.93,7,2400.97
155,1156,CA-2014-136567,2014-12-20 00:00:00,First Class,PS-19045,Penelope Sewall,Home Office,Harrisonburg,Virginia,22801.0,South,Furniture,Tables,2244.48,7,493.79
246,1247,CA-2014-168494,2014-12-12 00:00:00,Second Class,NP-18700,Nora Preis,Consumer,Fresno,California,93727.0,West,Furniture,Tables,3610.85,12,135.41
438,1439,CA-2015-139731,2015-10-15 00:00:00,Same Day,JE-15745,Joel Eaton,Consumer,Amarillo,Texas,79109.0,Central,Furniture,Chairs,2453.43,5,-350.49
454,1455,CA-2016-133711,2016-11-26 00:00:00,First Class,MC-17425,Mark Cousins,Corporate,Mobile,Alabama,36608.0,South,Technology,Machines,3040.00,8,1459.20

In [15]:
# find all loss transaction
df[df.profit < 0]

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
2,1003,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Furniture,Tables,1090.78,7,-290.88
7,1008,CA-2015-105312,2015-11-06 00:00:00,First Class,MT-17815,Meg Tillman,Consumer,Scottsdale,Arizona,NaN,West,Office Supplies,Binders,4.40,3,-3.52
27,1028,CA-2016-126529,2016-01-11 00:00:00,Second Class,DE-13255,Deanra Eno,Home Office,Springfield,Ohio,NaN,East,Technology,Phones,15.59,2,-9.87
34,1035,CA-2016-109820,2016-11-20 00:00:00,First Class,AG-10390,Allen Goldenen,Consumer,Cincinnati,Ohio,45231.0,East,Office Supplies,Binders,2.63,2,-1.93
35,1036,CA-2016-109820,2016-11-20 00:00:00,First Class,AG-10390,Allen Goldenen,Consumer,Cincinnati,Ohio,45231.0,East,Office Supplies,Binders,14.43,3,-10.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,1464,CA-2016-152289,2016-08-26 00:00:00,First Class,LC-16930,Linda Cazamias,Corporate,Pasadena,Texas,77506.0,Central,Furniture,Chairs,1024.72,6,-29.28
465,1466,CA-2014-151708,2014-08-08 00:00:00,Standard Class,MB-17305,Maria Bertelson,Consumer,Glendale,Arizona,85301.0,West,Furniture,Furnishings,121.38,4,-3.03
466,1467,CA-2014-151708,2014-08-08 00:00:00,Standard Class,MB-17305,Maria Bertelson,Consumer,Glendale,Arizona,85301.0,West,Technology,Accessories,95.98,3,-10.80
473,1474,US-2015-105676,2015-12-01 00:00:00,Same Day,NM-18520,Neoma Murray,Consumer,Houston,Texas,77036.0,Central,Furniture,Furnishings,6.69,4,-4.01
496,1497,CA-2017-152485,2017-09-04 00:00:00,Standard Class,JD-15790,John Dryer,Consumer,Coppell,Texas,75019.0,Central,Office Supplies,Storage,16.78,1,-0.21

In [16]:
df[df.category == "Furniture" ]

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
2,1003,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Furniture,Tables,1090.78,7,-290.88
10,1011,CA-2014-158540,2014-11-24 00:00:00,First Class,VG-21790,Vivek Gonzalez,Consumer,San Diego,California,NaN,West,Furniture,Furnishings,151.72,4,27.31
11,1012,CA-2017-118437,2017-06-17 00:00:00,Second Class,PF-19165,Philip Fox,Consumer,Olympia,Washington,NaN,West,Furniture,Furnishings,155.25,3,46.58
13,1014,US-2015-126214,2015-12-21 00:00:00,Second Class,JS-15880,John Stevenson,Consumer,Seattle,Washington,98103.0,West,Furniture,Tables,1618.37,13,356.04
16,1017,CA-2015-108665,2015-07-06 00:00:00,Standard Class,KM-16225,Kalyca Meade,Corporate,New York City,New York,10011.0,East,Furniture,Furnishings,13.96,2,6.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,1469,CA-2017-139199,2017-12-09 00:00:00,Standard Class,DK-12835,Damala Kotsonis,Corporate,Detroit,Michigan,48234.0,Central,Furniture,Chairs,872.94,3,226.96
473,1474,US-2015-105676,2015-12-01 00:00:00,Same Day,NM-18520,Neoma Murray,Consumer,Houston,Texas,77036.0,Central,Furniture,Furnishings,6.69,4,-4.01
488,1489,CA-2015-140410,2015-11-03 00:00:00,Standard Class,CM-12655,Corinna Mitchell,Home Office,Los Angeles,California,90008.0,West,Furniture,Furnishings,42.60,3,16.61
492,1493,CA-2017-166436,2017-11-24 00:00:00,Standard Class,TS-21370,Todd Sumrall,Corporate,New York City,New York,10035.0,East,Furniture,Chairs,977.29,6,173.74
493,1494,CA-2017-139661,2017-10-30 00:00:00,Standard Class,JW-15220,Jane Waco,Corporate,Vancouver,Washington,98661.0,West,Furniture,Furnishings,9.64,2,3.66

In [17]:
df[ (df.category == "Furniture") & (df.profit < 0 ) ]

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
2,1003,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Furniture,Tables,1090.78,7,-290.88
45,1046,CA-2017-152702,2017-10-12 00:00:00,Standard Class,SN-20710,Steve Nguyen,Home Office,Rockford,Illinois,61107.0,Central,Furniture,Chairs,254.60,14,-18.19
47,1048,CA-2016-169103,2016-03-08 00:00:00,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Miami,Florida,33142.0,South,Furniture,Furnishings,102.36,3,-3.84
50,1051,US-2015-153500,2015-07-03 00:00:00,First Class,DG-13300,Deirdre Greer,Corporate,Philadelphia,Pennsylvania,19134.0,East,Furniture,Furnishings,168.46,2,-29.48
60,1061,US-2015-125374,2015-03-23 00:00:00,Standard Class,JD-16060,Julia Dunbar,Consumer,Houston,Texas,77095.0,Central,Furniture,Chairs,107.77,2,-29.25
82,1083,US-2016-143819,2016-03-01 00:00:00,Standard Class,KD-16270,Karen Daniels,Consumer,Yonkers,New York,10701.0,East,Furniture,Tables,836.59,8,-264.92
106,1107,US-2016-110156,2016-11-19 00:00:00,Standard Class,EH-13945,Eric Hoffmann,Consumer,Houston,Texas,77041.0,Central,Furniture,Furnishings,2.33,2,-0.76
114,1115,CA-2017-140585,2017-12-18 00:00:00,Second Class,RA-19915,Russell Applegate,Consumer,Encinitas,California,92024.0,West,Furniture,Bookcases,119.83,1,-12.69
196,1197,US-2015-130519,2015-09-15 00:00:00,Same Day,NG-18355,Nat Gilpin,Corporate,Coral Springs,Florida,33065.0,South,Furniture,Furnishings,55.97,1,-2.10
198,1199,CA-2016-130946,2016-04-08 00:00:00,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,77041.0,Central,Furniture,Chairs,95.98,4,-4.11
212,1213,US-2017-118087,2017-09-09 00:00:00,Standard Class,SP-20620,Stefania Perrino,Corporate,Philadelphia,Pennsylvania,19134.0,East,Furniture,Chairs,141.37,2,-48.47
274,1275,CA-2016-119186,2016-05-26 00:00:00,Same Day,MS-17710,Maurice Satty,Consumer,Fort Worth,Texas,76106.0,Central,Furniture,Chairs,388.43,5,-88.78
310,1311,CA-2016-141397,2016-06-20 00:00:00,First Class,RC-19825,Roy Collins,Consumer,Pasadena,California,91104.0,West,Furniture,Chairs,161.57,2,-8.08
313,1314,US-2016-134488,2016-09-24 00:00:00,Standard Class,PK-19075,Pete Kriz,Consumer,Columbus,Ohio,43229.0,East,Furniture,Chairs,155.37,2,-13.32
350,1351,CA-2014-153976,2014-10-03 00:00:00,Second Class,BP-11290,Beth Paige,Consumer,Evanston,Illinois,60201.0,Central,Furniture,Chairs,258.28,3,-70.10
358,1359,CA-2017-160045,2017-04-26 00:00:00,First Class,LB-16735,Larry Blacks,Consumer,Fort Worth,Texas,76106.0,Central,Furniture,Furnishings,1.99,1,-1.44
367,1368,US-2017-155425,2017-11-10 00:00:00,First Class,AB-10600,Ann Blume,Corporate,Tucson,Arizona,85705.0,West,Furniture,Chairs,899.14,4,-146.11
369,1370,US-2015-103471,2015-12-24 00:00:00,Standard Class,JR-15670,Jim Radford,Consumer,Colorado Springs,Colorado,80906.0,West,Furniture,Bookcases,590.06,7,-786.74
381,1382,US-2016-100566,2016-09-03 00:00:00,Standard Class,JK-16120,Julie Kriz,Home Office,Aurora,Illinois,60505.0,Central,Furniture,Furnishings,83.95,3,-90.25
394,1395,US-2017-117247,2017-10-09 00:00:00,Standard Class,CK-12760,Cyma Kinney,Corporate,Aurora,Illinois,60505.0,Central,Furniture,Tables,652.45,5,-430.62
395,1396,US-2017-117247,2017-10-09 00:00:00,Standard Class,CK-12760,Cyma Kinney,Corporate,Aurora,Illinois,60505.0,Central,Furniture,Tables,66.65,3,-42.65
402,1403,US-2016-161396,2016-04-19 00:00:00,Standard Class,GM-14455,Gary Mitchum,Home Office,Columbus,Ohio,43229.0,East,Furniture,Tables,205.18,2,-58.13
405,1406,US-2014-118486,2014-04-06 00:00:00,First Class,SD-20485,Shirley Daniels,Home Office,Philadelphia,Pennsylvania,19143.0,East,Furniture,Tables,154.76,3,-36.11
409,1410,US-2016-122245,2016-09-25 00:00:00,Standard Class,AB-10105,Adrian Barton,Consumer,Phoenix,Arizona,85023.0,West,Furniture,Tables,393.17,3,-204.45
418,1419,CA-2015-126697,2015-09-21 00:00:00,First Class,SV-20815,Stuart Van,Corporate,Houston,Texas,77041.0,Central,Furniture,Furnishings,4.93,4,-1.48
438,1439,CA-2015-139731,2015-10-15 00:00:00,Same Day,JE-15745,Joel Eaton,Consumer,Amarillo,Texas,79109.0,Central,Furniture,Chairs,2453.43,5,-350.49
446,1447,CA-2017-102337,2017-06-13 00:00:00,First Class,SD-20485,Shirley Daniels,Home Office,Chicago,Illinois,60653.0,Central,Furniture,Chairs,470.30,7,-87.34
461,1462,US-2016-128902,2016-03-11 00:00:00,Standard Class,MB-18085,Mick Brown,Consumer,Vineland,New Jersey,8360.0,East,Furniture,Tables,244.01,2,-31.37
463,1464,CA-2016-152289,2016-08-26 00:00:00,First Class,LC-16930,Linda Cazamias,Corporate,Pasadena,Texas,77506.0,Central,Furniture,Chairs,1024.72,6,-29.28
465,1466,CA-2014-151708,2014-08-08 00:00:00,Standard Class,MB-17305,Maria Bertelson,Consumer,Glendale,Arizona,85301.0,West,Furniture,Furnishings,121.38,4,-3.03
473,1474,US-2015-105676,2015-12-01 00:00:00,Same Day,NM-18520,Neoma Murray,Consumer,Houston,Texas,77036.0,Central,Furniture,Furnishings,6.69,4,-4.01

In [18]:
df[ (df.category == "Furniture") | (df.profit < 0 ) ]

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
2,1003,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Furniture,Tables,1090.78,7,-290.88
7,1008,CA-2015-105312,2015-11-06 00:00:00,First Class,MT-17815,Meg Tillman,Consumer,Scottsdale,Arizona,NaN,West,Office Supplies,Binders,4.40,3,-3.52
10,1011,CA-2014-158540,2014-11-24 00:00:00,First Class,VG-21790,Vivek Gonzalez,Consumer,San Diego,California,NaN,West,Furniture,Furnishings,151.72,4,27.31
11,1012,CA-2017-118437,2017-06-17 00:00:00,Second Class,PF-19165,Philip Fox,Consumer,Olympia,Washington,NaN,West,Furniture,Furnishings,155.25,3,46.58
13,1014,US-2015-126214,2015-12-21 00:00:00,Second Class,JS-15880,John Stevenson,Consumer,Seattle,Washington,98103.0,West,Furniture,Tables,1618.37,13,356.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473,1474,US-2015-105676,2015-12-01 00:00:00,Same Day,NM-18520,Neoma Murray,Consumer,Houston,Texas,77036.0,Central,Furniture,Furnishings,6.69,4,-4.01
488,1489,CA-2015-140410,2015-11-03 00:00:00,Standard Class,CM-12655,Corinna Mitchell,Home Office,Los Angeles,California,90008.0,West,Furniture,Furnishings,42.60,3,16.61
492,1493,CA-2017-166436,2017-11-24 00:00:00,Standard Class,TS-21370,Todd Sumrall,Corporate,New York City,New York,10035.0,East,Furniture,Chairs,977.29,6,173.74
493,1494,CA-2017-139661,2017-10-30 00:00:00,Standard Class,JW-15220,Jane Waco,Corporate,Vancouver,Washington,98661.0,West,Furniture,Furnishings,9.64,2,3.66
496,1497,CA-2017-152485,2017-09-04 00:00:00,Standard Class,JD-15790,John Dryer,Consumer,Coppell,Texas,75019.0,Central,Office Supplies,Storage,16.78,1,-0.21

In [22]:
df[df.sales.between(10,12)]

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
24,1025,CA-2017-106964,2017-12-17 00:00:00,First Class,HR-14770,Hallie Redmond,Home Office,Los Angeles,California,90045.0,West,Office Supplies,Binders,11.81,2,4.28
53,1054,CA-2015-110667,2015-04-04 00:00:00,Standard Class,NF-18595,Nicole Fjeld,Home Office,New York City,New York,10009.0,East,Office Supplies,Art,11.16,2,4.35
62,1063,CA-2015-161263,2015-04-16 00:00:00,Standard Class,TS-21160,Theresa Swint,Corporate,Toledo,Ohio,43615.0,East,Office Supplies,Fasteners,10.42,7,-2.21
107,1108,US-2016-110156,2016-11-19 00:00:00,Standard Class,EH-13945,Eric Hoffmann,Consumer,Houston,Texas,77041.0,Central,Office Supplies,Binders,10.78,5,-17.25
111,1112,US-2016-110156,2016-11-19 00:00:00,Standard Class,EH-13945,Eric Hoffmann,Consumer,Houston,Texas,77041.0,Central,Office Supplies,Paper,10.37,2,3.63
127,1128,CA-2015-105970,2015-03-02 00:00:00,Standard Class,PA-19060,Pete Armstrong,Home Office,Richmond,Indiana,47374.0,Central,Office Supplies,Art,10.16,1,2.64
149,1150,CA-2015-112452,2015-04-04 00:00:00,Same Day,NC-18340,Nat Carroll,Consumer,Lansing,Michigan,48911.0,Central,Technology,Phones,10.95,1,0.44
160,1161,CA-2017-147039,2017-06-29 00:00:00,Standard Class,AA-10315,Alex Avila,Consumer,Minneapolis,Minnesota,55407.0,Central,Office Supplies,Binders,11.54,2,5.77
176,1177,CA-2014-120243,2014-12-27 00:00:00,Second Class,AT-10435,Alyssa Tate,Home Office,Los Angeles,California,90004.0,West,Office Supplies,Labels,11.56,4,5.43
206,1207,CA-2016-137050,2016-07-14 00:00:00,Second Class,SW-20755,Steven Ward,Corporate,New York City,New York,10009.0,East,Office Supplies,Storage,11.21,1,3.36
273,1274,CA-2016-119186,2016-05-26 00:00:00,Same Day,MS-17710,Maurice Satty,Consumer,Fort Worth,Texas,76106.0,Central,Office Supplies,Paper,10.37,2,3.63
323,1324,CA-2017-162635,2017-10-09 00:00:00,First Class,EB-14170,Evan Bailliet,Consumer,Wilmington,North Carolina,28403.0,South,Office Supplies,Paper,10.82,4,3.52
327,1328,CA-2016-128258,2016-03-30 00:00:00,First Class,CP-12085,Cathy Prescott,Corporate,Norwich,Connecticut,6360.0,East,Office Supplies,Paper,11.34,1,5.56
397,1398,CA-2016-124485,2016-11-24 00:00:00,First Class,NC-18340,Nat Carroll,Consumer,New York City,New York,10035.0,East,Office Supplies,Paper,11.56,2,5.66
404,1405,US-2014-118486,2014-04-06 00:00:00,First Class,SD-20485,Shirley Daniels,Home Office,Philadelphia,Pennsylvania,19143.0,East,Office Supplies,Supplies,10.30,1,-2.19
495,1496,CA-2017-152485,2017-09-04 00:00:00,Standard Class,JD-15790,John Dryer,Consumer,Coppell,Texas,75019.0,Central,Office Supplies,Art,10.19,7,3.19

In [25]:
df.category.unique()

array(['Office Supplies', 'Technology', 'Furniture'], dtype=object)

In [26]:
df.category.nunique()

3

In [27]:
df.category.value_counts()

category
Office Supplies    306
Furniture          107
Technology          87
Name: count, dtype: int64

In [29]:
# Top 10 cities with highest number of order count?
df.city.value_counts().head(10)

city
New York City    63
Los Angeles      36
Philadelphia     27
Houston          23
San Francisco    22
Seattle          16
Chicago          11
Jacksonville     11
Smyrna           11
Mesa             10
Name: count, dtype: int64

In [34]:
df.post_code.isnull().sum()

np.int64(16)

In [35]:
df.isnull().sum()

id               0
order_id         0
order_date       0
shipment         0
customer_id      0
name             0
segment          0
city             0
state            0
post_code       16
region           0
category         0
sub_category     0
sales            0
qty              0
profit           0
dtype: int64

In [37]:
df[df.post_code.isnull()]

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
1,1002,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18
2,1003,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Furniture,Tables,1090.78,7,-290.88
3,1004,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Office Supplies,Paper,19.44,3,9.33
4,1005,CA-2015-126445,2015-08-27 00:00:00,Standard Class,RA-19945,Ryan Akin,Consumer,Murrieta,California,NaN,West,Office Supplies,Storage,484.65,3,92.08
5,1006,CA-2015-111199,2015-11-13 00:00:00,Standard Class,JK-15730,Joe Kamberova,Consumer,Jacksonville,North Carolina,NaN,South,Office Supplies,Paper,115.30,3,40.35
6,1007,CA-2015-105312,2015-11-06 00:00:00,First Class,MT-17815,Meg Tillman,Consumer,Scottsdale,Arizona,NaN,West,Office Supplies,Envelopes,7.08,3,2.48
7,1008,CA-2015-105312,2015-11-06 00:00:00,First Class,MT-17815,Meg Tillman,Consumer,Scottsdale,Arizona,NaN,West,Office Supplies,Binders,4.40,3,-3.52
8,1009,US-2017-106705,2017-12-26 00:00:00,Standard Class,PO-18850,Patrick O'Brill,Consumer,Burlington,Iowa,NaN,Central,Office Supplies,Paper,44.75,5,20.59
9,1010,CA-2017-135034,2017-08-01 00:00:00,First Class,AT-10735,Annie Thurman,Consumer,Chicago,Illinois,NaN,Central,Technology,Phones,95.98,2,6.00
10,1011,CA-2014-158540,2014-11-24 00:00:00,First Class,VG-21790,Vivek Gonzalez,Consumer,San Diego,California,NaN,West,Furniture,Furnishings,151.72,4,27.31
11,1012,CA-2017-118437,2017-06-17 00:00:00,Second Class,PF-19165,Philip Fox,Consumer,Olympia,Washington,NaN,West,Furniture,Furnishings,155.25,3,46.58
12,1013,CA-2017-118437,2017-06-17 00:00:00,Second Class,PF-19165,Philip Fox,Consumer,Olympia,Washington,NaN,West,Office Supplies,Storage,14.03,1,4.07
27,1028,CA-2016-126529,2016-01-11 00:00:00,Second Class,DE-13255,Deanra Eno,Home Office,Springfield,Ohio,NaN,East,Technology,Phones,15.59,2,-9.87
41,1042,CA-2016-102981,2016-09-06 00:00:00,Second Class,MO-17500,Mary O'Rourke,Consumer,New York City,New York,NaN,East,Technology,Accessories,31.86,2,11.15
42,1043,CA-2016-102981,2016-09-06 00:00:00,Second Class,MO-17500,Mary O'Rourke,Consumer,New York City,New York,NaN,East,Furniture,Bookcases,722.35,3,90.29
43,1044,CA-2017-115651,2017-07-09 00:00:00,First Class,NS-18640,Noel Staavos,Corporate,Chicago,Illinois,NaN,Central,Office Supplies,Art,8.84,5,2.98

In [40]:
df[df.post_code.notnull()]

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
0,1001,CA-2016-155488,2016-11-13 00:00:00,Standard Class,FM-14290,Frank Merwin,Home Office,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
13,1014,US-2015-126214,2015-12-21 00:00:00,Second Class,JS-15880,John Stevenson,Consumer,Seattle,Washington,98103.0,West,Furniture,Tables,1618.37,13,356.04
14,1015,US-2015-126214,2015-12-21 00:00:00,Second Class,JS-15880,John Stevenson,Consumer,Seattle,Washington,98103.0,West,Technology,Accessories,99.60,1,36.85
15,1016,CA-2015-133025,2015-09-17 00:00:00,Second Class,MO-17800,Meg O'Connel,Home Office,Los Angeles,California,90036.0,West,Office Supplies,Paper,32.40,5,15.55
16,1017,CA-2015-108665,2015-07-06 00:00:00,Standard Class,KM-16225,Kalyca Meade,Corporate,New York City,New York,10011.0,East,Furniture,Furnishings,13.96,2,6.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1496,CA-2017-152485,2017-09-04 00:00:00,Standard Class,JD-15790,John Dryer,Consumer,Coppell,Texas,75019.0,Central,Office Supplies,Art,10.19,7,3.19
496,1497,CA-2017-152485,2017-09-04 00:00:00,Standard Class,JD-15790,John Dryer,Consumer,Coppell,Texas,75019.0,Central,Office Supplies,Storage,16.78,1,-0.21
497,1498,CA-2017-152485,2017-09-04 00:00:00,Standard Class,JD-15790,John Dryer,Consumer,Coppell,Texas,75019.0,Central,Office Supplies,Art,13.12,5,3.77
498,1499,CA-2016-141586,2016-10-17 00:00:00,First Class,NK-18490,Neil Knudson,Home Office,San Francisco,California,94122.0,West,Office Supplies,Binders,18.16,5,6.58
499,1500,CA-2017-130386,2017-11-12 00:00:00,Standard Class,NG-18430,Nathan Gelder,Consumer,Austin,Texas,78745.0,Central,Office Supplies,Paper,16.06,3,5.82

In [2]:
df.head(2)

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
0,1001,CA-2016-155488,2016-11-13 00:00:00,Standard Class,FM-14290,Frank Merwin,Home Office,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
1,1002,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18

In [5]:
df.rename(columns={"city":"location","name":"customer_name"})

,id,order_id,order_date,shipment,customer_id,customer_name,segment,location,state,post_code,region,category,sub_category,sales,qty,profit
0,1001,CA-2016-155488,2016-11-13 00:00:00,Standard Class,FM-14290,Frank Merwin,Home Office,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
1,1002,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18
2,1003,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Furniture,Tables,1090.78,7,-290.88
3,1004,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Office Supplies,Paper,19.44,3,9.33
4,1005,CA-2015-126445,2015-08-27 00:00:00,Standard Class,RA-19945,Ryan Akin,Consumer,Murrieta,California,NaN,West,Office Supplies,Storage,484.65,3,92.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1496,CA-2017-152485,2017-09-04 00:00:00,Standard Class,JD-15790,John Dryer,Consumer,Coppell,Texas,75019.0,Central,Office Supplies,Art,10.19,7,3.19
496,1497,CA-2017-152485,2017-09-04 00:00:00,Standard Class,JD-15790,John Dryer,Consumer,Coppell,Texas,75019.0,Central,Office Supplies,Storage,16.78,1,-0.21
497,1498,CA-2017-152485,2017-09-04 00:00:00,Standard Class,JD-15790,John Dryer,Consumer,Coppell,Texas,75019.0,Central,Office Supplies,Art,13.12,5,3.77
498,1499,CA-2016-141586,2016-10-17 00:00:00,First Class,NK-18490,Neil Knudson,Home Office,San Francisco,California,94122.0,West,Office Supplies,Binders,18.16,5,6.58
499,1500,CA-2017-130386,2017-11-12 00:00:00,Standard Class,NG-18430,Nathan Gelder,Consumer,Austin,Texas,78745.0,Central,Office Supplies,Paper,16.06,3,5.82

In [8]:
df = df.set_index("name")

In [9]:
df.head()

,id,order_id,order_date,shipment,customer_id,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
name,,,,,,,,,,,,,,,
Frank Merwin,1001,CA-2016-155488,2016-11-13 00:00:00,Standard Class,FM-14290,Home Office,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
Rick Hansen,1002,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Consumer,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18
Rick Hansen,1003,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Consumer,New York City,New York,NaN,East,Furniture,Tables,1090.78,7,-290.88
Rick Hansen,1004,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Consumer,New York City,New York,NaN,East,Office Supplies,Paper,19.44,3,9.33
Ryan Akin,1005,CA-2015-126445,2015-08-27 00:00:00,Standard Class,RA-19945,Consumer,Murrieta,California,NaN,West,Office Supplies,Storage,484.65,3,92.08

In [10]:
df.loc["Frank Merwin","city"]

'Vancouver'

In [18]:
cols = ["city","sales","profit"]
names = ["Rick Hansen","Frank Merwin"]
df.loc[names,cols]

                       city    sales  profit
name
Rick Hansen   New York City  2309.65  762.18
Rick Hansen   New York City  1090.78 -290.88
Rick Hansen   New York City    19.44    9.33
Frank Merwin      Vancouver    44.02   11.45

In [19]:
df.iloc[1,2]

'2015-07-31 00:00:00'

In [20]:
df.head()

,id,order_id,order_date,shipment,customer_id,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
name,,,,,,,,,,,,,,,
Frank Merwin,1001,CA-2016-155488,2016-11-13 00:00:00,Standard Class,FM-14290,Home Office,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
Rick Hansen,1002,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Consumer,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18
Rick Hansen,1003,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Consumer,New York City,New York,NaN,East,Furniture,Tables,1090.78,7,-290.88
Rick Hansen,1004,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Consumer,New York City,New York,NaN,East,Office Supplies,Paper,19.44,3,9.33
Ryan Akin,1005,CA-2015-126445,2015-08-27 00:00:00,Standard Class,RA-19945,Consumer,Murrieta,California,NaN,West,Office Supplies,Storage,484.65,3,92.08

In [22]:
df.iloc[1:4]

,id,order_id,order_date,shipment,customer_id,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
name,,,,,,,,,,,,,,,
Rick Hansen,1002,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Consumer,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18
Rick Hansen,1003,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Consumer,New York City,New York,NaN,East,Furniture,Tables,1090.78,7,-290.88
Rick Hansen,1004,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Consumer,New York City,New York,NaN,East,Office Supplies,Paper,19.44,3,9.33

In [23]:
df.index

Index(['Frank Merwin', 'Rick Hansen', 'Rick Hansen', 'Rick Hansen',
       'Ryan Akin', 'Joe Kamberova', 'Meg Tillman', 'Meg Tillman',
       'Patrick O'Brill', 'Annie Thurman',
       ...
       'Dionis Lloyd', 'Todd Sumrall', 'Todd Sumrall', 'Jane Waco',
       'Roy Franz', 'John Dryer', 'John Dryer', 'John Dryer', 'Neil Knudson',
       'Nathan Gelder'],
      dtype='object', name='name', length=500)

In [26]:
df = df.reset_index()

In [32]:
df.sales.sort_values(ascending=False)

85     4899.93
246    3610.85
454    3040.00
438    2453.43
1      2309.65
        ...
68        1.74
224       1.73
65        1.45
112       1.19
332       1.08
Name: sales, Length: 500, dtype: float64

In [36]:
df.sort_values(by='profit',ascending=False).head(3)

,name,id,order_id,order_date,shipment,customer_id,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
85,Karen Daniels,1086,US-2016-143819,2016-03-01 00:00:00,Standard Class,KD-16270,Consumer,Yonkers,New York,10701.0,East,Technology,Machines,4899.93,7,2400.97
454,Mark Cousins,1455,CA-2016-133711,2016-11-26 00:00:00,First Class,MC-17425,Corporate,Mobile,Alabama,36608.0,South,Technology,Machines,3040.00,8,1459.20
1,Rick Hansen,1002,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Consumer,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18

In [2]:
df.groupby("region")['sales'].sum()

region
Central    20251.94
East       33839.93
South      22457.49
West       31414.47
Name: sales, dtype: float64

In [5]:
df.groupby("city")['profit'].sum().sort_values(ascending=False).head(10)

city
New York City     2658.81
Yonkers           2253.43
Mobile            1556.70
Los Angeles       1169.29
Washington         974.31
Smyrna             688.72
Seattle            658.25
Harrisonburg       623.20
Pleasant Grove     576.56
Jonesboro          437.25
Name: profit, dtype: float64

In [7]:
df.groupby(['region',"category"])[['sales','profit','qty']].sum()

                            sales   profit  qty
region  category
Central Furniture         8677.98  -734.09   91
        Office Supplies   4508.01 -1705.29  237
        Technology        7065.95  1196.06   70
East    Furniture        10458.06   638.08  119
        Office Supplies   8048.40  1948.55  335
        Technology       15333.47  4180.48   97
South   Furniture         8109.74  1509.78   72
        Office Supplies   4608.60  1177.54  209
        Technology        9739.15  2423.03   74
West    Furniture        14366.56    94.19  132
        Office Supplies   9660.79  1796.99  381
        Technology        7387.12   860.61  102

In [8]:
df.groupby("category").agg({"sales":"sum","profit":"mean"})

                    sales     profit
category
Furniture        41612.34  14.093084
Office Supplies  26825.80  10.515654
Technology       39525.69  99.542299

In [11]:
df.pivot_table(index='region',columns="category",values='sales',aggfunc="sum")

category  Furniture  Office Supplies  Technology
region
Central     8677.98          4508.01     7065.95
East       10458.06          8048.40    15333.47
South       8109.74          4608.60     9739.15
West       14366.56          9660.79     7387.12

In [2]:
emp= pd.read_csv("employee.csv")
dep = pd.read_csv("department.csv")

In [18]:
emp.columns = [i.lower() for i in emp.columns]
dep.columns = [i.lower() for i in dep.columns]

In [19]:
emp

   employee_id employee_name  department_id  salary  manager_id
0          101          Ravi              1   50000       105.0
1          102         Kunal              2   90000       105.0
2          103         Umang              1   30000       107.0
3          104          Ravi              2   78000       107.0
4          105        Shivam              2   73000       107.0
5          106        Kartik              3   90000       105.0
6          107         Kunal              8   35000         NaN

In [20]:
dep

   department_id department name departmrnt_head building
0              1           Sales          Piyush        A
1              2       Marketing          Rakesh        K
2              5      Production           Mohan        T

In [21]:
pd.merge(emp,dep,on="department_id",how="inner")

,employee_id,employee_name,department_id,salary,manager_id,department name,departmrnt_head,building
0,101,Ravi,1,50000,105.0,Sales,Piyush,A
1,102,Kunal,2,90000,105.0,Marketing,Rakesh,K
2,103,Umang,1,30000,107.0,Sales,Piyush,A
3,104,Ravi,2,78000,107.0,Marketing,Rakesh,K
4,105,Shivam,2,73000,107.0,Marketing,Rakesh,K

In [4]:
pd.concat([emp,emp])

   Employee_id Employee_name  Department_id  Salary  manager_id
0          101          Ravi              1   50000       105.0
1          102         Kunal              2   90000       105.0
2          103         Umang              1   30000       107.0
3          104          Ravi              2   78000       107.0
4          105        Shivam              2   73000       107.0
5          106        Kartik              3   90000       105.0
6          107         Kunal              8   35000         NaN
0          101          Ravi              1   50000       105.0
1          102         Kunal              2   90000       105.0
2          103         Umang              1   30000       107.0
3          104          Ravi              2   78000       107.0
4          105        Shivam              2   73000       107.0
5          106        Kartik              3   90000       105.0
6          107         Kunal              8   35000         NaN

In [5]:
df.head(2)

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit
0,1001,CA-2016-155488,2016-11-13 00:00:00,Standard Class,FM-14290,Frank Merwin,Home Office,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45
1,1002,CA-2015-124891,2015-07-31 00:00:00,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            500 non-null    int64
 1   order_id      500 non-null    object
 2   order_date    500 non-null    object
 3   shipment      500 non-null    object
 4   customer_id   500 non-null    object
 5   name          500 non-null    object
 6   segment       500 non-null    object
 7   city          500 non-null    object
 8   state         500 non-null    object
 9   post_code     484 non-null    float64
 10  region        500 non-null    object
 11  category      500 non-null    object
 12  sub_category  500 non-null    object
 13  sales         500 non-null    float64
 14  qty           500 non-null    int64
 15  profit        500 non-null    float64
dtypes: float64(3), int64(2), object(11)
memory usage: 62.6+ KB

In [8]:
df['order_date'] =  pd.to_datetime(df.order_date)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            500 non-null    int64
 1   order_id      500 non-null    object
 2   order_date    500 non-null    datetime64[ns]
 3   shipment      500 non-null    object
 4   customer_id   500 non-null    object
 5   name          500 non-null    object
 6   segment       500 non-null    object
 7   city          500 non-null    object
 8   state         500 non-null    object
 9   post_code     484 non-null    float64
 10  region        500 non-null    object
 11  category      500 non-null    object
 12  sub_category  500 non-null    object
 13  sales         500 non-null    float64
 14  qty           500 non-null    int64
 15  profit        500 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(10)
memory usage: 62.6+ KB

In [10]:
df['year'] = df.order_date.dt.year

In [11]:
df.head(2)

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit,year
0,1001,CA-2016-155488,2016-11-13,Standard Class,FM-14290,Frank Merwin,Home Office,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45,2016
1,1002,CA-2015-124891,2015-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18,2015

In [12]:
df['month_name'] = df.order_date.dt.month_name()
df.head(2)

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit,year,month_name
0,1001,CA-2016-155488,2016-11-13,Standard Class,FM-14290,Frank Merwin,Home Office,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45,2016,November
1,1002,CA-2015-124891,2015-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18,2015,July

In [13]:
df['week day'] = df.order_date.dt.day_name()
df.head(2)

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit,year,month_name,week day
0,1001,CA-2016-155488,2016-11-13,Standard Class,FM-14290,Frank Merwin,Home Office,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45,2016,November,Sunday
1,1002,CA-2015-124891,2015-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18,2015,July,Friday

In [16]:
# Filter using date column
df[df.order_date > "2017-1-1"]

,id,order_id,order_date,shipment,customer_id,name,segment,city,state,post_code,region,category,sub_category,sales,qty,profit,year,month_name,week day
8,1009,US-2017-106705,2017-12-26,Standard Class,PO-18850,Patrick O'Brill,Consumer,Burlington,Iowa,NaN,Central,Office Supplies,Paper,44.75,5,20.59,2017,December,Tuesday
9,1010,CA-2017-135034,2017-08-01,First Class,AT-10735,Annie Thurman,Consumer,Chicago,Illinois,NaN,Central,Technology,Phones,95.98,2,6.00,2017,August,Tuesday
11,1012,CA-2017-118437,2017-06-17,Second Class,PF-19165,Philip Fox,Consumer,Olympia,Washington,NaN,West,Furniture,Furnishings,155.25,3,46.58,2017,June,Saturday
12,1013,CA-2017-118437,2017-06-17,Second Class,PF-19165,Philip Fox,Consumer,Olympia,Washington,NaN,West,Office Supplies,Storage,14.03,1,4.07,2017,June,Saturday
24,1025,CA-2017-106964,2017-12-17,First Class,HR-14770,Hallie Redmond,Home Office,Los Angeles,California,90045.0,West,Office Supplies,Binders,11.81,2,4.28,2017,December,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,1494,CA-2017-139661,2017-10-30,Standard Class,JW-15220,Jane Waco,Corporate,Vancouver,Washington,98661.0,West,Furniture,Furnishings,9.64,2,3.66,2017,October,Monday
495,1496,CA-2017-152485,2017-09-04,Standard Class,JD-15790,John Dryer,Consumer,Coppell,Texas,75019.0,Central,Office Supplies,Art,10.19,7,3.19,2017,September,Monday
496,1497,CA-2017-152485,2017-09-04,Standard Class,JD-15790,John Dryer,Consumer,Coppell,Texas,75019.0,Central,Office Supplies,Storage,16.78,1,-0.21,2017,September,Monday
497,1498,CA-2017-152485,2017-09-04,Standard Class,JD-15790,John Dryer,Consumer,Coppell,Texas,75019.0,Central,Office Supplies,Art,13.12,5,3.77,2017,September,Monday
499,1500,CA-2017-130386,2017-11-12,Standard Class,NG-18430,Nathan Gelder,Consumer,Austin,Texas,78745.0,Central,Office Supplies,Paper,16.06,3,5.82,2017,November,Sunday

In [17]:
df.to_csv("final data file.csv")

In [20]:
df.groupby("city")['sales'].sum().to_csv("city_data.csv")

In [21]:
df.groupby("city")['sales'].sum()

city
Amarillo       2717.31
Antioch          19.44
Arlington        93.36
Aurora          942.47
Austin           18.83
                ...
Vineland        244.01
Washington     2670.19
Westminster      31.97
Wilmington       10.82
Yonkers        6125.82
Name: sales, Length: 110, dtype: float64