# Pandas Library

In [ ]:
# pip install pandas

In [1]:
import pandas as pd
import numpy as np

# Series

In [ ]:
s = pd.Series([230,450,980,500,1200])
print(s)

In [ ]:
# Try  +   -    *    /  //   **  %

s / 2

In [ ]:
sales = pd.Series([450,230,890])
cost = pd.Series([120,78,360])

sales -cost       # profit

# Indexing and slicing

In [ ]:
print(s)

In [ ]:
s[2]

In [ ]:
s[2] = 500

In [ ]:
s

In [ ]:
# Negative indexing does not work in the series 
s[-1]

In [ ]:
print(s)

In [ ]:
s[1:4]

# Name index

In [ ]:
age = pd.Series({"rohan":34,"kunal":78,"kartik":23,"mohit":12,"naman":46})
print(age)

In [ ]:
age[0]

In [ ]:
age['kunal']

In [ ]:
age['kunal'] = 44

In [ ]:
age['abc'] = 56

In [ ]:
age

In [ ]:
print(age)

In [ ]:
age['kunal':'mohit']

In [ ]:
new  = pd.Series([45,32,12,76],index=[7,4,7,9])
new

In [ ]:
new[4]

In [ ]:
new[7]

In [ ]:
age

In [ ]:
age < 40

In [ ]:
age[age<40]

# Attributes in Pandas series

In [ ]:
age

In [ ]:
age.index

In [ ]:
age.values

In [ ]:
age.dtype

In [ ]:
age.shape

In [ ]:
age.size

In [ ]:
age.ndim

In [ ]:
age.name

In [ ]:
age.name = "Customer Age"

In [ ]:
age

# Aggregate functions in series

In [ ]:
sales = pd.Series([560,340,210,980,564,340,340])
sales

In [ ]:
sales.sum()

In [ ]:
sales.min()

In [ ]:
sales.max()

In [ ]:
sales.mean()    # average

In [ ]:
sales.median()

In [ ]:
sales.mode()

In [ ]:
sales.std()

In [ ]:
sales.var()

In [ ]:
sales.count()

In [ ]:
sales.quantile(0.25)     # Q1

In [ ]:
sales.quantile(0.75)     # Q3

In [ ]:
sales.describe()

# np.where

In [ ]:
import numpy as np

print(sales)

a = np.where(sales>=500 , "good", "bad")
pd.Series(a)

# apply method

In [ ]:
sales = pd.Series([560,340,210,980,564,340,340])
print(sales)

In [ ]:
sales = pd.Series([560,340,210,980,564,340,340])
print(sales)

def find_category(amount):
    if amount<400:
        return "Low"
    elif amount < 700:
        return "Mid"
    else:
        return "High"

sales.apply(find_category)

In [ ]:
print(sales)
sales.apply(lambda amount : amount*0.05 if amount<=500 else amount*0.10)

# Getting the Data from files

In [ ]:
ls

In [ ]:
import os
os.listdir()

In [ ]:
os.getcwd()

In [2]:
# if the file is in same folder 
df = pd.read_csv("store.csv")

In [ ]:
print(r"C:\Users\deves\Documents\GitHub\Free_Datasets\Data Sets\diabetes.csv")

In [ ]:
r"C:\Users\deves\Documents\GitHub\Free_Datasets\Data Sets\tip.csv"

In [ ]:
# if file is not in the same folder 
df = pd.read_csv(r"C:\Users\deves\Documents\GitHub\Free_Datasets\Data Sets\tip.csv")
df.head(2)

In [ ]:
# from excel file
orders = pd.read_excel("global_superstore.xlsx")
orders.head(2)

In [ ]:
returns = pd.read_excel("global_superstore.xlsx",sheet_name="Returns")
returns.head()

In [ ]:
data = pd.read_excel("global_superstore.xlsx",sheet_name=["Orders","Returns"])

In [ ]:
data['Returns']

In [ ]:
# from google sheets
url="https://docs.google.com/spreadsheets/d/1zdiRkCfTwW8DL2CqyCQ8oLobM9w6G0zYSKM8KBHGlh4/edit?usp=sharing"

url = url.replace("/edit?usp=sharing", "/export?format=csv")
df = pd.read_csv(url)
df.head()

In [ ]:
# pip install sqlalchemy

In [ ]:
# pip install pymysql

In [ ]:
# pip install mysql-connector-python

In [ ]:
# From Database - MySQL

import sqlalchemy as sql
import pandas as pd

user = "root"
password = "1234"
host = "localhost"
database = "db"

engine = sql.create_engine(f"mysql+mysqlconnector://{user}:{password}@{host}/{database}")
pd.read_sql("select name,sales,profit from store;",engine)

# Know about your data

In [ ]:
df

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.describe().round(2)

In [ ]:
df.head(2)

In [ ]:
df.tail(2)

In [ ]:
df.sample(5)

In [ ]:
# check null values
df.isnull()

In [ ]:
df.isnull().sum()

In [ ]:
# getting a list of all columns
df.columns

# selecting single columns

In [ ]:
df

In [ ]:
# single column
df['name']

In [ ]:
df['sales']

In [ ]:
# shortcut way to getting a column
df.sales

# Selecting multiple columns

In [ ]:
df[['name','sales','profit']]

# Creating new columns

In [ ]:
df.head(2)

In [ ]:
df['new']

In [ ]:
df['new'] = 100

In [4]:
df['cost'] = df['sales'] - df['profit']

In [5]:
df.head(2)

,order_id,order_date,name,city,state,post_code,region,category,sub_category,sales,qty,profit,cost
0,CA-2016-155488,2016-11-13 00:00:00,Frank Merwin,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45,32.57
1,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18,1547.47

In [ ]:
# create a new column unit price (sales/qty)

In [6]:
# creating new column sales category using np.where If the sales amount is above 1000 it is high else low?  

df['sales_category'] = np.where(df['sales']>=1000 ,"High","Low")
df.head()

,order_id,order_date,name,city,state,post_code,region,category,sub_category,sales,qty,profit,cost,sales_category
0,CA-2016-155488,2016-11-13 00:00:00,Frank Merwin,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45,32.57,Low
1,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18,1547.47,High
2,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Furniture,Tables,1090.78,7,-290.88,1381.66,High
3,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Office Supplies,Paper,19.44,3,9.33,10.11,Low
4,CA-2015-126445,2015-08-27 00:00:00,Ryan Akin,Murrieta,California,NaN,West,Office Supplies,Storage,484.65,3,92.08,392.57,Low

In [ ]:
# Create a new column PNL(Profit and Loss) using profit column

In [8]:
# Create a new column with values Yes and No if the transaction where the category is furniture and we have face a loss then its a yes else no?
df['new'] = np.where((df.category == "Furniture") & (df.profit <0 ) , "yes","No")
df.head()

,order_id,order_date,name,city,state,post_code,region,category,sub_category,sales,qty,profit,cost,sales_category,new
0,CA-2016-155488,2016-11-13 00:00:00,Frank Merwin,Vancouver,Washington,98661.0,West,Office Supplies,Art,44.02,2,11.45,32.57,Low,No
1,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Technology,Accessories,2309.65,7,762.18,1547.47,High,No
2,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Furniture,Tables,1090.78,7,-290.88,1381.66,High,yes
3,CA-2015-124891,2015-07-31 00:00:00,Rick Hansen,New York City,New York,NaN,East,Office Supplies,Paper,19.44,3,9.33,10.11,Low,No
4,CA-2015-126445,2015-08-27 00:00:00,Ryan Akin,Murrieta,California,NaN,West,Office Supplies,Storage,484.65,3,92.08,392.57,Low,No

In [ ]:
# Create a new column for sales category low Medium and High?
def sales_cat(amount):
    if amount <= 100:
        return "Low"
    elif amount <= 1000:
        return "Mid"
    else:
        return "High"

df['sales_category'] = df['sales'].apply(sales_cat)
df.head()

In [ ]:
df.head()

In [ ]:
# apply function on df
def furniture_disc(row):
    if row['category'] == "Furniture" :
        return row['sales']*15/100
    else :
        return 0

df['furniture_discount'] = df.apply(furniture_disc,axis=1)

df.head()

# delete columns and rows

In [ ]:
df.drop(columns="city")   # temp

In [ ]:
df.head(2)

In [ ]:
df = df.drop(columns="sales_category")   # permanent delete

In [ ]:
# delete multiple columns
df.drop(columns=["city",'name','profit','new'])

In [ ]:
df.head()

In [ ]:
df.drop(index=2)

In [ ]:
df.drop(index=[0,2,3])

In [ ]:
del df['new']

In [ ]:
df.head(2)

# Rename a column

In [ ]:
df.head(2)

In [ ]:
df.rename(columns={"city":"location","region":"new_region"})

In [ ]:
df.rename(index={0:"first"})

In [ ]:
df.columns

In [ ]:
for i in range(5):
    print(i*2)

In [ ]:
[i*2 for i in range(5)]

In [ ]:
{i:i**2 for i in range(1,11)}

In [ ]:
{i:i.upper() for i in df.columns}

In [ ]:
for i in df.columns:
    print(i,i.upper())

In [ ]:
df.rename(columns={ i : i.upper() for i in df.columns})

# Filter DataFrame

In [ ]:
df

In [ ]:
df['sales'] > 3000

In [ ]:
df[df['sales'] > 3000]

In [ ]:
df[df['region'] == "East"]

In [ ]:
# Filter all the records where subcategory is Paper

In [ ]:
# show all the records where we have loss

In [ ]:
df[df['sub_category'].isin(['Art',"Paper","Tables"])]

In [ ]:
# filter using null values
df[df['post_code'].isnull()]

In [ ]:
df[df['post_code'].notnull()]

In [ ]:
df.query("sales > 3000 and region == 'East'")

In [ ]:
# Show all the records where the category's furniture and the sales amount is above 2000

In [ ]:
# Filter using multiple columns
#   df[ (condition) & | (condition) ]

df[(df.sales > 1000) & (df.region == "East") ]

# loc and iloc

In [ ]:
# df.loc[row,column]
df.loc["Rick Hansen"]

In [ ]:
df.loc["Rick Hansen","sales"]

In [ ]:
df.loc["Rick Hansen",["sales",'profit','qty']]

In [ ]:
df.loc[["Rick Hansen","Becky Martin"],"sales"]

In [ ]:
df.loc[["Rick Hansen","Becky Martin"],["sales","profit"]]

In [ ]:
df.head()

In [ ]:
#  iloc
df.iloc[6]

In [ ]:
df.iloc[1,2]

In [ ]:
# find top 10 rows from data
df.iloc[0:11]

In [ ]:
df.iloc[[0,7,23]]

# Index

In [ ]:
df.head()

In [ ]:
df = df.set_index("name")

In [ ]:
df.head()

In [ ]:
df['name']

In [ ]:
df.index

In [ ]:
df = df.reset_index()

# Check Unique Values

In [ ]:
# check unique values in a columns
df = pd.read_csv("store.csv")

In [ ]:
df.head()

In [ ]:
df['region']

In [ ]:
df['region'].unique()

In [ ]:
df['city'].unique()

In [ ]:
df['region'].nunique()

In [ ]:
df['city'].nunique()

In [ ]:
df['category'].value_counts()

In [ ]:
df.nunique()

In [ ]:
df[["region","category","name","state"]].nunique()

In [ ]:
# Find top five cities with highest number of orders?

In [ ]:
# Find total number of unique customers

In [ ]:
# create a list/array of all the subcategories in the data?

# Handling Missing Data

In [ ]:
df.isnull().sum()

In [ ]:
df['post_code']

In [ ]:
df['post_code'].isnull()

In [ ]:
df['post_code'].isna()     # same as isnull()

In [ ]:
df['post_code'].fillna("050505")
# df['post_code'] = df['post_code'].fillna("050505")   -> to make it permanent

In [ ]:
df['post_code'].value_counts()

In [ ]:
df['post_code'].mode()[0]

In [ ]:
df['post_code'].fillna(df['post_code'].mode()[0])

In [ ]:
df.dropna(subset="post_code")

In [ ]:
df.dropna()
# df = df.dropna()  -> to make it permanent

# Sort data

In [ ]:
df.head()

In [ ]:
df['sales']

In [ ]:
df['sales'].sort_values()

In [ ]:
df['sales'].sort_values(ascending=False)

In [ ]:
# sort name column in ascending order

In [ ]:
df.sort_values(by="sales")

In [ ]:
df.sort_values(by="sales",ascending=False)

In [ ]:
# Find top five highest profit transaction 
df.sort_values(by="profit",ascending=False).head()

In [ ]:
# top 3 highest sales orders info ?

In [ ]:
# top 5 most profitable order in west region ?

In [ ]:
# Sorting using multiple columns
df.sort_values(by="category")

In [ ]:
df.sort_values(by=["category","sub_category"])

In [ ]:
df.sort_values(by=["sub_category","sales"],ascending=True)

In [ ]:
df.sort_values(by=["sub_category","sales"],ascending=[True,False])

In [ ]:
# sorting on the basis of index

In [ ]:
df2 = df.set_index("name")

In [ ]:
df2

In [ ]:
df2.sort_index()

In [ ]:
df2.sort_index(ascending=False)

# Group by

In [ ]:
df = pd.read_csv("store.csv")
df.head()

In [ ]:
df['sales'].sum()

In [ ]:
df.groupby("category")['sales'].sum()

In [ ]:
# Find region wise total profit

In [ ]:
# Find sub_category wise total sales

In [ ]:
# Find city wise total sales and show only top 10
df.groupby("city")['sales'].sum().sort_values(ascending=False).head(10)

In [ ]:
# Top five most profitable customers ?

In [ ]:
# Top five sub category by total sales in East region ?

# gropu by with multiple columns

In [ ]:
df.groupby("category")[['sales','profit']].sum()

In [ ]:
df.groupby(['category','sub_category'])['sales'].sum()

In [ ]:
df.groupby(['category','sub_category'])[['sales','profit','qty']].sum()

In [ ]:
# Show region then category wise total sales

In [ ]:
# Groupby with different aggregation

In [ ]:
df.groupby("category")['sales'].agg("sum")

In [ ]:
df.groupby("category")['sales'].agg(['sum','mean','count'])

In [ ]:
df.groupby("category")[['sales','profit']].agg(['sum','mean','count'])

In [ ]:
df.groupby("category").agg({'sales':'sum',"qty":"mean"})

In [ ]:
df.groupby("category").agg({'sales':['sum',"max"],"qty":"mean"})

# Pivot tables

In [ ]:
df.pivot_table(
    index="category",
    columns="region",
    values='sales',
    aggfunc="sum"
)

# DateTime

In [ ]:
df.info()

In [ ]:
df.head(2)

In [ ]:
# change it to datetime
pd.to_datetime(df['order_date'])

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [ ]:
df.info()

In [ ]:
df['year'] = df['order_date'].dt.year
df.head(2)

In [ ]:
df['quarter'] =  df['order_date'].dt.quarter
df.head(2)

In [ ]:
df['month'] = df['order_date'].dt.month
df.head(2)

In [ ]:
df['month_name'] = df['order_date'].dt.month_name()
df.head(2)

In [ ]:
df['day'] = df['order_date'].dt.day
df.head(2)

In [ ]:
df['day_name'] = df['order_date'].dt.day_name()
df.head(2)

In [ ]:
# filter using date
df['order_date'] == "2015-07-31"

In [ ]:
df[df['order_date'] == "2015-07-31"]

In [ ]:
df[df['order_date'] < "2015-07-31"]

In [ ]:
# find data between 2015-1-1 and 2015-5-31
df[
    (df['order_date'] >= "2015-1-1")
    & 
    (df['order_date'] <= "2015-5-31")
]

In [ ]:
# find all the records from year 2015

In [ ]:
# get all the data after 1-1-2017 ?

In [ ]:
# category wise total sales for each year (pivot table)
df.pivot_table(index='category',columns='year',values='sales',aggfunc="sum")

In [ ]:
# find month wise number of orders ?
df['month_name'].value_counts()

In [ ]:
# df['quarter'].apply(lambda x : "Q"+ str(x))

In [ ]:
# df.groupby(['year','quarter'])['sales'].sum()

# Duplicate values

# Working with two or more files

In [ ]:
# merge
emp = pd.read_csv("employee.csv")
dep = pd.read_csv("department.csv")

In [ ]:
emp

In [ ]:
dep

In [ ]:
pd.merge(emp,dep,on='department_id')

In [ ]:
pd.merge(emp,dep,on='department_id',how='left')

In [ ]:
pd.merge(emp,dep,on='department_id',how='right')

In [ ]:
pd.merge(emp,dep,on='department_id',how='outer')

In [ ]:
# when the same column has different name in both table
emp = emp.rename(columns={"department_id":"depid"})

In [ ]:
emp.head(2)

In [ ]:
dep.head(2)

In [ ]:
pd.merge(emp,dep,left_on="depid",right_on='department_id')

In [ ]:
# append data 
sales2019 = pd.read_csv("sales_2019.csv")
sales2019

In [ ]:
sales2020 = pd.read_csv("sales_2020.csv")
sales2020

In [ ]:
sales2021 = pd.read_csv("sales_2021.csv")
sales2021

In [ ]:
pd.concat([sales2019,sales2020,sales2021])

# Save data in files

In [ ]:
final = pd.concat([sales2019,sales2020,sales2021])

In [ ]:
final

In [ ]:
final.to_csv("final.csv")

In [ ]:
final.to_excel("final.xlsx")

In [ ]:
ls