# Logistic regression model

In [ ]:
# Get dataset - https://www.kaggle.com/datasets/yasserh/titanic-dataset?resource=download

In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder , StandardScaler

In [ ]:
ls

In [ ]:
df=  pd.read_csv("Titanic-Dataset.csv")
df.head()

## Feature selection

In [43]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin',
       'Embarked'],
      dtype='object')

In [ ]:
col = ['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 
       'Parch', 'Fare', 'Cabin', 'Embarked']

df = df[col]

In [ ]:
df.head()

# data cleaning

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df.isnull().sum()

In [ ]:
for i in df.columns:
    print(df[i].value_counts())
    print()

In [ ]:
df['Cabin'].unique()

In [ ]:
# keeping only the first char
df['Cabin']  = df.Cabin.str.slice(0,1)

In [ ]:
df.Cabin.value_counts()

In [ ]:
df.Cabin

In [ ]:
df['Cabin'] =  df.Cabin.fillna("Na")

In [ ]:
df.head()

In [ ]:
pd.crosstab(df['Cabin'],df['Embarked'])

In [ ]:
# cleaning age column
df.Age.describe()

In [ ]:
df['Age'] = df['Age'].fillna(29)

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
# cleaning Embarked column
df['Embarked'].value_counts()

In [ ]:
df['Embarked'] = df['Embarked'].fillna("S")

In [ ]:
df.info()

# spliting the data

In [45]:
x = df.drop(columns="Survived")
y = df['Survived']

In [56]:
x_train, x_test, y_train, y_test = sk.model_selection.train_test_split(x,y,test_size=0.2,random_state=1)

In [57]:
print(x_train.shape)
x_train.head(2)

(712, 8)

     Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
301       3    male  29.0      2      0  23.2500    Na        Q
309       1  female  30.0      0      0  56.9292     E        C

In [58]:
print(x_test.shape)
x_test.head(2)

(179, 8)

     Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
862       1  female  48.0      0      0  25.9292     D        S
223       3    male  29.0      0      0   7.8958    Na        S

In [59]:
print(y_train.shape)
y_train.head(2)

(712,)

301    1
309    1
Name: Survived, dtype: int64

In [60]:
print(y_test.shape)
y_test.head()

(179,)

862    1
223    0
84     1
680    0
535    1
Name: Survived, dtype: int64

## using column transformer 
to transform data numerical and categorical

In [65]:
num = x.select_dtypes(include=np.number).columns
cat = x.select_dtypes(include="object").columns

In [66]:
print(num)
print(cat)

Index(['Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')
Index(['Sex', 'Cabin', 'Embarked'], dtype='object')

In [ ]:
transformed_data = sk.compose.ColumnTransformer(
    [
        ("scaler",)
    ]
)